### ISSUE TITLE
Document GeoLocation toString()

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/java-api-client#23]
I had a 'bug' during development because I didn't overwrite the toString() of a GeoLocation implementation, had to log out network call to see that the geolocation paramater was incorrect in the url.

I think it would be good practice in general to add toString() to the interfaces explicitly where their value would be used for any logic, not just logging. I think it's part of the contract of this interface.
It doesn't force the class with compilation error to implement it, but still it would be much more apparent that we need to do it.

**Comment by dmfs** [comment]
I think we should take the opposite direction and don't make use to `toString()` anymore. Instead we should have `CharSequence` or `Uri` adapters and use it like so:
```
CharSequence geo = new LatLngText(goeLocation);
Uri geoUri = new GeoUri(geoLocation);
```

**Comment by lemonboston** [comment]
Yes, I like that, too. After all, how a geo location is added to an uri should probably be an independent thing from modelling it. Certainly not part of a general `toString()` (even if there would be a `toStringValue()` that would still be to general). Geo location could be formatted to string in multiple ways, so the independent decorator/adapter approach looks better here as well.

Feel free to rename this ticket if you see fit.
