### ISSUE TITLE
Support GET Categories API request

### ISSUE THREAD

**Issue by dmfs** [schedjoules/java-api-client#31]
In order to get localized display names for all known categories, as a developer I want an ApiQuery to retrieve the categories supported by the API.
---

**Comment by lemonboston** [comment]
@rutgerg The category labels are not translated yet, right?
I get the English versions when I make the request with different language header:

```
curl -XGET -H 'Authorization: Token token="0443a55244bb2b6224fd48e0416f0d9c"' -H "Accept-Language: de-DE" -H "Content-type: application/json" 'https://api.schedjoules.com/categories?u=testtesttesttesttest'
```

**Comment by rutgerg** [comment]
Not yet https://github.com/schedjoules/event-discovery-backend/issues/73

**Comment by lemonboston** [comment]
Ok, thanks
