### ISSUE TITLE
Remove direct dependencies that are transitive as well?

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/java-api-client#46]
@dmfs Should we remove dependency declarations for libs that are included transitively from another lib anyway?

```
compile 'org.dmfs:iterators:' + ITERATORS
compile 'org.dmfs:optional:'+ OPTIONAL
compile 'org.dmfs:rfc3986-uri:0.7'
```
`uri` uses `optional` which uses `iterators`. 
(Plus there are the `http-client-essentials` modules as well, I haven't checked them)

**Comment by dmfs** [comment]
No. If we use classes from these packages in the SDK. Our project should not rely on dependencies to provide other dependencies we use. E.g. if the SDK uses uri-toolkit it should be declared as a dependency.

**Comment by dmfs** [comment]
Also, the SDK might require a certain minimum version of a dependency whereas the dependencies might depend on an older version which doesn't provide a class we use in the SDK.

**Comment by lemonboston** [comment]
Ah, I see, your last comment makes it clear. No need to force libraries to update to newer versions of the dependency in question if they are backward compatible and the library is fine with the old one.
Thanks.
